/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomNavbar: typeof import('./../components/base/CustomNavbar.vue')['default']
    HistoryCellDeliverDistributor: typeof import('./../components/history-cells/HistoryCellDeliverDistributor.vue')['default']
    HistoryCellDeliverStore: typeof import('./../components/history-cells/HistoryCellDeliverStore.vue')['default']
    HistoryCellInventoryScan: typeof import('./../components/history-cells/HistoryCellInventoryScan.vue')['default']
    HistoryCellReceiveScan: typeof import('./../components/history-cells/HistoryCellReceiveScan.vue')['default']
    HistoryCellReturnHq: typeof import('./../components/history-cells/HistoryCellReturnHq.vue')['default']
    HistoryCellSamplingCheck: typeof import('./../components/history-cells/HistoryCellSamplingCheck.vue')['default']
    HistoryCellStoreRequisition: typeof import('./../components/history-cells/HistoryCellStoreRequisition.vue')['default']
    HistoryCellStoreReturn: typeof import('./../components/history-cells/HistoryCellStoreReturn.vue')['default']
    HistoryCellTransferIn: typeof import('./../components/history-cells/HistoryCellTransferIn.vue')['default']
    HistoryCellTransferOut: typeof import('./../components/history-cells/HistoryCellTransferOut.vue')['default']
    HistoryDetail: typeof import('./../components/common/history-detail/index.vue')['default']
    HistoryRecordList: typeof import('./../components/HistoryRecordList.vue')['default']
    ItemContent: typeof import('./../components/common/ItemContent.vue')['default']
    LangSelect: typeof import('./../components/common/LangSelect.vue')['default']
    ManualInput: typeof import('./../components/common/ManualInput.vue')['default']
    PressFeedback: typeof import('./../components/base/PressFeedback.vue')['default']
    PrivacyInfo: typeof import('./../components/privacy/PrivacyInfo.vue')['default']
    PrivacyPopup: typeof import('./../components/privacy/PrivacyPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../components/base/SearchBar.vue')['default']
    SearchBox: typeof import('./../components/common/SearchBox.vue')['default']
    StatusPage: typeof import('./../components/common/StatusPage.vue')['default']
  }
}
