export default {
  maxHeaderLength: 100,
  defaultType: 'feat',
  defaultScope: '',
  scopes: [
    'admin',
    'web',
    'miniapp',
    'api',
    'shared',
    'sdk',
    'ui',
    'server',
    'configs',
    'infra',
    'docs',
    'repo',
  ],
  types: [
    { value: 'feat', name: 'feat:     新功能' },
    { value: 'fix', name: 'fix:      修复问题' },
    { value: 'refactor', name: 'refactor: 重构代码' },
    { value: 'perf', name: 'perf:     性能优化' },
    { value: 'style', name: 'style:    代码风格调整' },
    { value: 'docs', name: 'docs:     文档更新' },
    { value: 'test', name: 'test:     测试相关' },
    { value: 'build', name: 'build:    构建系统或依赖' },
    { value: 'ci', name: 'ci:       CI/CD 配置' },
    { value: 'chore', name: 'chore:    杂项维护' },
    { value: 'revert', name: 'revert:   回滚提交' },
  ],
  messages: {
    type: '选择提交类型:',
    scope: '选择影响范围:',
    customScope: '输入自定义 scope:',
    subject: '填写简短描述:\n',
    body: '填写详细描述，可选。使用 "|" 换行:\n',
    breaking: '列出 BREAKING CHANGES，可选:\n',
    footerPrefixesSelect: '选择关联 issue 前缀，可选:',
    customFooterPrefix: '输入自定义 footer 前缀:',
    footer: '填写关联 issue，例如 #123，可选:\n',
    confirmCommit: '确认提交?',
  },
  allowCustomScopes: true,
  allowBreakingChanges: ['feat', 'fix'],
  issuePrefixes: [{ value: '#', name: 'issues: #' }],
  subjectLimit: 100,
  breaklineNumber: 100,
  upperCaseSubject: false,
}
