/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomNavbar: typeof import('./../components/base/CustomNavbar.vue')['default']
    LangSelect: typeof import('./../components/common/LangSelect.vue')['default']
    ManualInput: typeof import('./../components/common/ManualInput.vue')['default']
    PressFeedback: typeof import('./../components/base/PressFeedback.vue')['default']
    PrivacyInfo: typeof import('./../components/privacy/PrivacyInfo.vue')['default']
    PrivacyPopup: typeof import('./../components/privacy/PrivacyPopup.vue')['default']
    SearchBar: typeof import('./../components/base/SearchBar.vue')['default']
    SearchBox: typeof import('./../components/common/SearchBox.vue')['default']
    StatusPage: typeof import('./../components/common/StatusPage.vue')['default']
  }
}
