export enum MiniErrorCode {
  Unauthorized = 'UNAUTHORIZED',
  PhoneRequired = 'PHONE_REQUIRED',
  Forbidden = 'FORBIDDEN',
  EventSeriesNotFound = 'EVENT_SERIES_NOT_FOUND',
  ScheduleNotFound = 'SCHEDULE_NOT_FOUND',
  RegistrationClosed = 'REGISTRATION_CLOSED',
  RegistrationFull = 'REGISTRATION_FULL',
  AlreadyRegistered = 'ALREADY_REGISTERED',
  RegistrationNotFound = 'REGISTRATION_NOT_FOUND',
  RegistrationCancelClosed = 'REGISTRATION_CANCEL_CLOSED',
  CheckInNotOpen = 'CHECK_IN_NOT_OPEN',
  CheckInQrInvalid = 'CHECK_IN_QR_INVALID',
  CheckInExpired = 'CHECK_IN_EXPIRED',
  AlreadyCheckedIn = 'ALREADY_CHECKED_IN',
  RegistrationRequired = 'REGISTRATION_REQUIRED',
  RateLimited = 'RATE_LIMITED',
  InternalError = 'INTERNAL_ERROR',
  NetworkUnstable = 'NETWORK_UNSTABLE',
}
